modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/CyberDay1/TheExpanseV2/issues"

[[mods]]
modId="verticalexpansion"
version="${file.jarVersion}"
displayName="The Expanse V2"
description='''Vertical world expansion and advanced terrain generation'''

authors="Cyber3D"
logoFile="logo.png"
displayURL="https://github.com/CyberDay1/TheExpanseV2"

[[dependencies.verticalexpansion]]
modId="neoforge"
mandatory=true
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.verticalexpansion]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.21.10]"
ordering="NONE"
side="BOTH"
