modLoader="javafml"
loaderVersion="[4,)"          # FML 4 = NeoForge 21.1.x

license="MIT"
issueTrackerURL="https://github.com/CyberDay1/TheExpanseV2/issues"
showAsResourcePack=false

[[mods]]
modId="verticalexpansion"
version="${file.jarVersion}"
displayName="The Expanse V2"
displayURL="https://github.com/CyberDay1/TheExpanseV2"
logoFile=""
credits=""
authors="Cyber3D"
description='''
Vertical world expansion and advanced terrain generation:
- Extended build height & depth
- Custom terrain / tectonic shaping
- Deep oceans, wide rivers, ravines, waterfalls
'''

[[mixins]]
config="verticalexpansion.mixins.json"

# === Dependencies ===

[[dependencies.verticalexpansion]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.verticalexpansion]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.10]"
ordering="NONE"
side="BOTH"
